name: Download google sheets and push to core-curriculum-data

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Download google sheets and push to core-curriculum-data
    runs-on: ubuntu-latest
    env:
      GAUTH_TYPE: ${{secrets.GAUTH_TYPE}}
      GAUTH_PROJECT_ID: ${{secrets.GAUTH_PROJECT_ID}}
      GAUTH_PRIVATE_KEY_ID: ${{secrets.GAUTH_PRIVATE_KEY_ID}}
      GAUTH_PRIVATE_KEY: ${{secrets.GAUTH_PRIVATE_KEY}}
      GAUTH_CLIENT_EMAIL: ${{secrets.GAUTH_CLIENT_EMAIL}}
      GAUTH_CLIENT_ID: ${{secrets.GAUTH_CLIENT_ID}}
      GAUTH_AUTH_URI: ${{secrets.GAUTH_AUTH_URI}}
      GAUTH_TOKEN_URI: ${{secrets.GAUTH_TOKEN_URI}}
      GAUTH_AUTH_PROVIDER_X509_CERT_URL: ${{secrets.GAUTH_AUTH_PROVIDER_X509_CERT_URL}}
      GAUTH_CLIENT_X509_CERT_URL: ${{secrets.GAUTH_CLIENT_X509_CERT_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1   
      - name: Checkout output in data repo
        uses: actions/checkout@v3
        with:
          repository: ncukondo/core-curriculum-data
          token: ${{ secrets.GH_PAT }}
          path: output_in_github
          fetch-depth: 1  
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: download sheets and make output
        run: make output
      - name: commit and push
        run: |
          cd output_in_github
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            echo change ditected update reposistory
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Updated from Google Sheets"
            git push
          else
            echo no change
          fi

